### ISSUE TITLE
Decide and implement secure token approach

### ISSUE THREAD

**Issue by anjackson** [ukwa/npld-player#1]
The NPLD Player must send a secure token with every request to the upstream server, so that the client application can be authenticated before the request is passed on to the PyWB instance that is handling playback.

Ideally, this could be done by Ensuring an additional header is sent with every request (e.g. HTTP `Bearer` token).

In Puppeteer, this has not always been reliable [^1] . If this turns out to be the case here,  an alternative is to use proxy authentication. See https://stackoverflow.com/questions/50497982/basic-proxy-authentication-on-electron for an example of specifying a proxy with a login from an Electron app.

[^1]: We've seen headers not being set by ServiceWorkers, and we've seen the knowledge of additional headers being sent as e.g. `Access-Control-Request-Headers: warcprox-meta` and this can break websites, [see here](https://github.com/ukwa/webrender-puppeteer/blob/425697d9ffd885a84eab6730da7e1f971145c1e7/renderer.js#L81-L87).

**Comment by ikreymer** [comment]
Hm, is there a particular requirement for proxy-based replay vs standard rewriting replay?

What I was thinking was that the NPLD player can act more like a kiosk, the replay would be handled by the upstream pywb instance, eg. `https://www.webarchive.org.uk/wayback/npld-access/<ts>/<url>` and it could pass a custom header,
which could be validated in an nginx instance.

It should be possible to add an arbitrary header to any request through Electron via:
https://www.electronjs.org/docs/latest/api/web-request (can double-check that this works).

For the special live resources, they can also be proxied through pywb (which will also wrap them in a custom viewer if necessary).

Would this address all the use cases or am I missing something?

**Comment by anjackson** [comment]
Yeah, your assessment is right, and I've tried to re-word the ticket to make it clearer. I've had some problems ensuring requests are always intercepted, but hopefully that was just a Puppeteer problem.  I think there might be some faffing around to make sure you have the HTTP Session of the WebView, but again I'm going on a fuzzy memory. I'm sure you'll be able to work it out.

**Comment by ikreymer** [comment]
Would an nginx-level access control be sufficient, eg. if an auth token is not included, the nginx blocks access to pywb, and the app will set the token? If its for the entire collection, that might be sufficient.

Otherwise, can also use something like [X-Pywb-ACL-User header](https://pywb.readthedocs.io/en/latest/manual/access-control.html#user-based-access-controls) to allow selective access, though that might not be needed if this is for the entire collection only.

**Comment by anjackson** [comment]
@ikreymer Yes, NGINX-level is sufficient, and indeed preferred as it keeps things separate.
