### ISSUE TITLE
Initial webview replay loading setup

### ISSUE THREAD

**Issue by ikreymer** [ukwa/npld-player#7]
The app will read build-time settings, such as prefix and auth token, and use them for accessing the replay.
URLs entered in location bar will then load from the specified prefix.

- [x] setup webview with history nav support

**Comment by SuaYoo** [comment]
@ikreymer what is the reason behind the requirement to use `<webview>` vs `BrowserView`? [Electron docs](https://www.electronjs.org/docs/latest/api/webview-tag#webviewcangoback) have this warning:

> We currently recommend to not use the webview tag and to consider alternatives, like iframe, [Electron's BrowserView](https://www.electronjs.org/docs/latest/api/browser-view), or an architecture that avoids embedded content altogether.

**Comment by ikreymer** [comment]
> @ikreymer what is the reason behind the requirement to use `<webview>` vs `iframe` or `BrowserView`? [Electron docs](https://www.electronjs.org/docs/latest/api/webview-tag#webviewcangoback) have this warning:
> 
> > We currently recommend to not use the webview tag and to consider alternatives, like iframe, [Electron's BrowserView](https://www.electronjs.org/docs/latest/api/browser-view), or an architecture that avoids embedded content altogether.

Yeah, this has been the recommendation for a number of years, but it seems webview support is generally pretty good in the latest versions. The reason for not using iframe is to be able to have a separate session for the contents.
The BrowserView is more cumbersome to work with, and would require responding to nav events in the main process and more interprocess communication.
We can definitely revisit if run into any issues

**Comment by ikreymer** [comment]
Breaking out the rest of the things into their own issues

**Comment by ikreymer** [comment]
This is done!
